"""add task_type_id to task

Revision ID: 17730b748f1d
Revises: 9bac20eabc3d
Create Date: 2026-04-04 14:52:17.073513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17730b748f1d'
down_revision = '9bac20eabc3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('task_type_id')

    # ### end Alembic commands ###
