"""add experimental_group user

Revision ID: 9bac20eabc3d
Revises: c791a44445c5
Create Date: 2026-04-03 10:18:09.805875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bac20eabc3d'
down_revision = 'c791a44445c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experimental_group', sa.String(length=20), server_default='control', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('experimental_group')

    # ### end Alembic commands ###
