"""add late_minutes submission

Revision ID: c791a44445c5
Revises: 5ba3232795b5
Create Date: 2026-04-02 15:43:31.085700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c791a44445c5'
down_revision = '5ba3232795b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_minutes', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('late_minutes')

    # ### end Alembic commands ###
